In [1]:
lst = [10,20,30]
print(lst)

[10, 20, 30]


In [5]:
# import module
import numpy as np

In [6]:
# Create list and display the same
my_list=[10,20,30]
print(my_list)

[10, 20, 30]


In [7]:
# Display list in the form of array
arr=np.array(my_list)
arr

array([10, 20, 30])

In [8]:
# Create matrix/array of given list elements
my_mat=[[10,20,30],[40,50,60],[70,80,90]]
np.array(my_mat)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
# display the numbers from 0 to 10 arange function exclude the 2nd range number
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Gives all the even numbers from o to 10 
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
# Create one dimensional array with value 0
np.zeros(3)

array([0., 0., 0.])

In [15]:
# Create two dimensional array with value 0
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# Create one dimensional array with value 1
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
#Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
 # 11 evenly spaced points
np.linspace(0,5,11) 

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [20]:
#numpy also creates arrays of random numbers
np.random.rand(5)

array([0.53892277, 0.86910052, 0.79892103, 0.61688933, 0.51386078])

In [22]:
#It will give 10 random numbers from 1 to 100
np.random.randint(1,100,10)

array([30, 52, 85, 70, 22, 14, 18, 76, 84, 82])

In [23]:
#It will give 1 random numbers from 1 to 100
np.random.randint(1,100)

11

In [24]:
#It will print numbers from 0 to 24
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
# By using reshape we can create matrix of array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
# Gives random 10 integer elements from range 0 to 49 because it excludes 50
randarr=np.random.randint(0,50,10)
randarr

array([31, 43, 16, 20, 43, 35, 46, 48, 34, 37])

In [31]:
# finds maximum number from random array
randarr.max()

48

In [32]:
# finds minimum number from random array
randarr.min()

16

In [33]:
#Gives maximum array index
randarr.argmax()

7

In [34]:
#Gives minimum array index
randarr.argmin()

2

In [ ]:
lst = [10,20,30,40,50]
arr1=np.array(lst)
arr1